require('dotenv').config();
const path = require('path');
const {
  JWT_SECRET,
  ACCESS_TOKEN_TIME,
  SALT_ROUNDS,
  DEFAULT_CUSTOMER_EMAIL,
  DEFAULT_CUSTOMER_PASSWORD,
  DEFAULT_CREATOR_EMAIL,
  DEFAULT_CREATOR_PASSWORD,
} = process.env;

module.exports = {
  JWT_SECRET,
  ACCESS_TOKEN_TIME,
  SALT_ROUNDS: +SALT_ROUNDS || 5,
  DEFAULT_CUSTOMER_EMAIL: DEFAULT_CUSTOMER_EMAIL || 'userBuyer@mail.com',
  DEFAULT_CUSTOMER_PASSWORD: DEFAULT_CUSTOMER_PASSWORD || 'userBuyer@mail.com',
  DEFAULT_CREATOR_EMAIL: DEFAULT_CREATOR_EMAIL || 'userCreator@mail.com',
  DEFAULT_CREATOR_PASSWORD: DEFAULT_CREATOR_PASSWORD || 'userCreator@mail.com',
  SQUADHELP_BANK_NUMBER: '4564654564564564',
  SQUADHELP_BANK_NAME: 'SquadHelp',
  SQUADHELP_BANK_CVC: '453',
  SQUADHELP_BANK_EXPIRY: '11/26',
  USER_ROLES: {
    CUSTOMER: 'customer',
    CREATOR: 'creator',
  },
  CREATOR_ENTRIES: 'creator_entries',
  CONTEST_STATUSES: {
    CONTEST_STATUS_ACTIVE: 'active',
    CONTEST_STATUS_FINISHED: 'finished',
    CONTEST_STATUS_PENDING: 'pending',
  },
  CONTEST_TYPES: {
    NAME_CONTEST: 'name',
    LOGO_CONTEST: 'logo',
    TAGLINE_CONTEST: 'tagline',
  },
  OFFER_STATUSES: {
    OFFER_STATUS_PENDING: 'pending',
    OFFER_STATUS_REJECTED: 'rejected',
    OFFER_STATUS_WON: 'won',
  },
  DEV_FILES_PATH: path.resolve(__dirname, '..', 'public/'),
  PROD_FILES_PATH: '/var/www/html',
  SOCKET_CONNECTION: 'connection',
  SOCKET_SUBSCRIBE: 'subscribe',
  SOCKET_UNSUBSCRIBE: 'unsubscribe',
  NOTIFICATION_ENTRY_CREATED: 'onEntryCreated',
  NOTIFICATION_CHANGE_MARK: 'changeMark',
  NOTIFICATION_CHANGE_OFFER_STATUS: 'changeOfferStatus',
  NEW_MESSAGE: 'newMessage',
  CHANGE_BLOCK_STATUS: 'CHANGE_BLOCK_STATUS',
};
